from fastapi import APIRouter, File
from fastapi.responses import FileResponse, Response

import logging
import requests
from starlette.background import BackgroundTasks

from model_inference import perform_inference, perform_inference_url, select_server, clean_annotations
from auth import SignatureAuth
from config.constants import SMARTDATA_ENDPOINT

from schemas import *
import json
from pprint import pprint

router = APIRouter()


@router.post("/solar_panel_defect/polygons", tags=["solar_panel_defect"])
async def return_polygons(file: bytes = File(...)):
    select_server('solar')

    logging.info(f"Getting polygons for file")
    img, mask, contours = perform_inference(file)
    pprint(contours)
    pprint(clean_annotations(annotations=contours))
    return clean_annotations(annotations=contours)


@router.post("/solar_panel_defect/masked-image", tags=["solar_panel_defect"])
async def return_polygons(file: bytes = File(...)):
    select_server('solar')

    logging.info(f"Getting polygons for file")
    img, mask, contours = perform_inference(file)
    img.save('img.jpg')
    mask.save('mask.jpg')
    return FileResponse('img.jpg')


@router.post("/solar_panel_defect/{dataset_uuid}", tags=["solar_panel_defect"])
async def solar_panel_defect_detection(dataset_uuid: str, image_urls: InspectionViewImages,
                         background_tasks: BackgroundTasks) -> Response:
    """
    Runs solar panel defect detection on the supplied dataset's inspection view.
    :param dataset_uuid: dataset in Smartdata that solar panel defect detection is being applied to
    :param image_urls: URLs of images to perform detection on
    :param background_tasks: background thread worker to process the images after response
    :return: Http response OK
    @author Conor Brosnan <c.brosnan@nationaldrones.com>
    """

    select_server('solar')

    logging.info(f"Detecting solar panel defects for dataset_uuid {dataset_uuid}")
    background_tasks.add_task(process_solar_panel_defect_detection,
                              dataset_uuid=dataset_uuid, inspection_view_images=image_urls)
    return Response()


async def process_solar_panel_defect_detection(dataset_uuid: str, inspection_view_images: InspectionViewImages) -> None:
    """
    Processes supplied images with solar panel defect detection and saves the results to Smartdata dataset
    :param dataset_uuid: dataset to save the autogenerated annotations to in Smartdata
    :param inspection_view_images: images to process with solar panel defect detection
    :return:
    @author Joe Mudryk <j.mudryk@nationaldrones.com>
    """
    inspection_view_annotations = InspectionViewAnnotations(dataset_uuid=dataset_uuid, image_annotations_list=[])
    logging.info(f"Getting solar panel defect detection results for dataset_uuid: {dataset_uuid}")

    for image_no, image in enumerate(inspection_view_images.images, start=1):
        logging.info(f"Running solar panel defect detection on image {image_no}/{len(inspection_view_images.images)}: {image.url}")
        try:
            _, _, annotations = perform_inference_url(image.url)
            logging.info(f"Total Annotations found = {len(annotations)}")
            logging.debug(f"Annotations found = {annotations}")

            # convert the annotations to a more consistent structure
            converted_annotations = clean_annotations(annotations=annotations)
            # Convert annotations coordinates to leaflet ratio
            for annotation in converted_annotations:
                if len(annotation) > 0:
                    for coord in annotation:
                        ratio = 2250 / image.height
                        temp = coord[0] * ratio
                        coord[0] = 2250 - coord[1] * ratio
                        coord[1] = temp

            if len(annotations) > 0:
                # Call smartdata to add the annotations, this is done per image otherwise the request is too large
                logging.debug(
                    f"Sending {len(converted_annotations)} solar panel defect annotations to smartdata for image {image.url}")
                response = requests.post(f"{SMARTDATA_ENDPOINT}/save_autogenerated_rust_annotations/{image.uuid}/",
                                         data=json.dumps(converted_annotations), auth=SignatureAuth())
                if response.status_code != 200:
                    logging.error(f"Smartdata save annotation response: {response.text}")
                    with open("log_output.html", "w") as file:
                        file.write(response.text)
                logging.info("Solar panel defect annotation created in smartdata")
            else:
                logging.debug(f"No solar panel defects detected in image {image.url}")
        except Exception as e:
            logging.error(f"Failed get the solar panel defect annotations for image "
                          f"{image_no}/{len(inspection_view_images.images)}: {image.url}")
            logging.error(e)

    # Send an email to the user about the solar panel defect detection being complete
    response = requests.post(f"{SMARTDATA_ENDPOINT}/send_rust_detection_complete_email/{dataset_uuid}/",
                             inspection_view_annotations.json(), auth=SignatureAuth())
    if response.status_code != 200:
        logging.error(f"Smartdata failed to send solar panel defect detection complete email to user: {response.text}")

    logging.info(f"Completed solar panel defect detection for dataset_uuid: {dataset_uuid}")
